// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: commands.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_INBOUND  ConnectionType = 0
	ConnectionType_OUTBOUND ConnectionType = 1
	ConnectionType_USER     ConnectionType = 2
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "INBOUND",
		1: "OUTBOUND",
		2: "USER",
	}
	ConnectionType_value = map[string]int32{
		"INBOUND":  0,
		"OUTBOUND": 1,
		"USER":     2,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

type NetType int32

const (
	NetType_HTTP NetType = 0
	NetType_TCP  NetType = 1
	NetType_UDP  NetType = 2
)

// Enum value maps for NetType.
var (
	NetType_name = map[int32]string{
		0: "HTTP",
		1: "TCP",
		2: "UDP",
	}
	NetType_value = map[string]int32{
		"HTTP": 0,
		"TCP":  1,
		"UDP":  2,
	}
)

func (x NetType) Enum() *NetType {
	p := new(NetType)
	*p = x
	return p
}

func (x NetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetType) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[1].Descriptor()
}

func (NetType) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[1]
}

func (x NetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetType.Descriptor instead.
func (NetType) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

type RotateJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateJournalRequest) Reset() {
	*x = RotateJournalRequest{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateJournalRequest) ProtoMessage() {}

func (x *RotateJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateJournalRequest.ProtoReflect.Descriptor instead.
func (*RotateJournalRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

type RotateJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateJournalResponse) Reset() {
	*x = RotateJournalResponse{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateJournalResponse) ProtoMessage() {}

func (x *RotateJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateJournalResponse.ProtoReflect.Descriptor instead.
func (*RotateJournalResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

type ConnectionIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesRx       uint64                 `protobuf:"varint,1,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	BytesTx       uint64                 `protobuf:"varint,2,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	BytesPerSecRx uint64                 `protobuf:"varint,3,opt,name=bytes_per_sec_rx,json=bytesPerSecRx,proto3" json:"bytes_per_sec_rx,omitempty"`
	BytesPerSecTx uint64                 `protobuf:"varint,4,opt,name=bytes_per_sec_tx,json=bytesPerSecTx,proto3" json:"bytes_per_sec_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionIO) Reset() {
	*x = ConnectionIO{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionIO) ProtoMessage() {}

func (x *ConnectionIO) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionIO.ProtoReflect.Descriptor instead.
func (*ConnectionIO) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionIO) GetBytesRx() uint64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *ConnectionIO) GetBytesTx() uint64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *ConnectionIO) GetBytesPerSecRx() uint64 {
	if x != nil {
		return x.BytesPerSecRx
	}
	return 0
}

func (x *ConnectionIO) GetBytesPerSecTx() uint64 {
	if x != nil {
		return x.BytesPerSecTx
	}
	return 0
}

type StatsMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ConnectionType         `protobuf:"varint,1,opt,name=type,proto3,enum=xraymon.commands.ConnectionType" json:"type,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Io            *ConnectionIO          `protobuf:"bytes,3,opt,name=io,proto3" json:"io,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsMeta) Reset() {
	*x = StatsMeta{}
	mi := &file_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMeta) ProtoMessage() {}

func (x *StatsMeta) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMeta.ProtoReflect.Descriptor instead.
func (*StatsMeta) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

func (x *StatsMeta) GetType() ConnectionType {
	if x != nil {
		return x.Type
	}
	return ConnectionType_INBOUND
}

func (x *StatsMeta) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *StatsMeta) GetIo() *ConnectionIO {
	if x != nil {
		return x.Io
	}
	return nil
}

type NetworkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StatsMeta           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatsResponse) Reset() {
	*x = NetworkStatsResponse{}
	mi := &file_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatsResponse) ProtoMessage() {}

func (x *NetworkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatsResponse.ProtoReflect.Descriptor instead.
func (*NetworkStatsResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkStatsResponse) GetStats() []*StatsMeta {
	if x != nil {
		return x.Stats
	}
	return nil
}

type NetworkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatsRequest) Reset() {
	*x = NetworkStatsRequest{}
	mi := &file_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatsRequest) ProtoMessage() {}

func (x *NetworkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatsRequest.ProtoReflect.Descriptor instead.
func (*NetworkStatsRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{5}
}

type ConnectionJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          uint64                 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionJournalRequest) Reset() {
	*x = ConnectionJournalRequest{}
	mi := &file_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionJournalRequest) ProtoMessage() {}

func (x *ConnectionJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionJournalRequest.ProtoReflect.Descriptor instead.
func (*ConnectionJournalRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectionJournalRequest) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

type ConnectionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Proto         NetType                `protobuf:"varint,3,opt,name=proto,proto3,enum=xraymon.commands.NetType" json:"proto,omitempty"`
	Inbound       string                 `protobuf:"bytes,4,opt,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound      string                 `protobuf:"bytes,5,opt,name=outbound,proto3" json:"outbound,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMeta) Reset() {
	*x = ConnectionMeta{}
	mi := &file_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMeta) ProtoMessage() {}

func (x *ConnectionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMeta.ProtoReflect.Descriptor instead.
func (*ConnectionMeta) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionMeta) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ConnectionMeta) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ConnectionMeta) GetProto() NetType {
	if x != nil {
		return x.Proto
	}
	return NetType_HTTP
}

func (x *ConnectionMeta) GetInbound() string {
	if x != nil {
		return x.Inbound
	}
	return ""
}

func (x *ConnectionMeta) GetOutbound() string {
	if x != nil {
		return x.Outbound
	}
	return ""
}

func (x *ConnectionMeta) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CoreStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusRequest) Reset() {
	*x = CoreStatusRequest{}
	mi := &file_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusRequest) ProtoMessage() {}

func (x *CoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusRequest.ProtoReflect.Descriptor instead.
func (*CoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{8}
}

type CoreStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Working       bool                   `protobuf:"varint,1,opt,name=working,proto3" json:"working,omitempty"`
	LastLog       string                 `protobuf:"bytes,2,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	WorkingTime   *durationpb.Duration   `protobuf:"bytes,3,opt,name=working_time,json=workingTime,proto3" json:"working_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusResponse) Reset() {
	*x = CoreStatusResponse{}
	mi := &file_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusResponse) ProtoMessage() {}

func (x *CoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusResponse.ProtoReflect.Descriptor instead.
func (*CoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{9}
}

func (x *CoreStatusResponse) GetWorking() bool {
	if x != nil {
		return x.Working
	}
	return false
}

func (x *CoreStatusResponse) GetLastLog() string {
	if x != nil {
		return x.LastLog
	}
	return ""
}

func (x *CoreStatusResponse) GetWorkingTime() *durationpb.Duration {
	if x != nil {
		return x.WorkingTime
	}
	return nil
}

type CoreRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreRestartRequest) Reset() {
	*x = CoreRestartRequest{}
	mi := &file_commands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreRestartRequest) ProtoMessage() {}

func (x *CoreRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreRestartRequest.ProtoReflect.Descriptor instead.
func (*CoreRestartRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{10}
}

type CoreRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreRestartResponse) Reset() {
	*x = CoreRestartResponse{}
	mi := &file_commands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreRestartResponse) ProtoMessage() {}

func (x *CoreRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreRestartResponse.ProtoReflect.Descriptor instead.
func (*CoreRestartResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{11}
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_commands_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{12}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_commands_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UploadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RestartCore   bool                   `protobuf:"varint,2,opt,name=restart_core,json=restartCore,proto3" json:"restart_core,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigRequest) Reset() {
	*x = UploadConfigRequest{}
	mi := &file_commands_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigRequest) ProtoMessage() {}

func (x *UploadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigRequest.ProtoReflect.Descriptor instead.
func (*UploadConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{14}
}

func (x *UploadConfigRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UploadConfigRequest) GetRestartCore() bool {
	if x != nil {
		return x.RestartCore
	}
	return false
}

type UploadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigResponse) Reset() {
	*x = UploadConfigResponse{}
	mi := &file_commands_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigResponse) ProtoMessage() {}

func (x *UploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigResponse.ProtoReflect.Descriptor instead.
func (*UploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{15}
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\x10xraymon.commands\x1a\x1egoogle/protobuf/duration.proto\"\x16\n" +
	"\x14RotateJournalRequest\"\x17\n" +
	"\x15RotateJournalResponse\"\x96\x01\n" +
	"\fConnectionIO\x12\x19\n" +
	"\bbytes_rx\x18\x01 \x01(\x04R\abytesRx\x12\x19\n" +
	"\bbytes_tx\x18\x02 \x01(\x04R\abytesTx\x12'\n" +
	"\x10bytes_per_sec_rx\x18\x03 \x01(\x04R\rbytesPerSecRx\x12'\n" +
	"\x10bytes_per_sec_tx\x18\x04 \x01(\x04R\rbytesPerSecTx\"\x87\x01\n" +
	"\tStatsMeta\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .xraymon.commands.ConnectionTypeR\x04type\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12.\n" +
	"\x02io\x18\x03 \x01(\v2\x1e.xraymon.commands.ConnectionIOR\x02io\"I\n" +
	"\x14NetworkStatsResponse\x121\n" +
	"\x05stats\x18\x01 \x03(\v2\x1b.xraymon.commands.StatsMetaR\x05stats\"\x15\n" +
	"\x13NetworkStatsRequest\".\n" +
	"\x18ConnectionJournalRequest\x12\x12\n" +
	"\x04last\x18\x01 \x01(\x04R\x04last\"\xbb\x01\n" +
	"\x0eConnectionMeta\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12/\n" +
	"\x05proto\x18\x03 \x01(\x0e2\x19.xraymon.commands.NetTypeR\x05proto\x12\x18\n" +
	"\ainbound\x18\x04 \x01(\tR\ainbound\x12\x1a\n" +
	"\boutbound\x18\x05 \x01(\tR\boutbound\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\"\x13\n" +
	"\x11CoreStatusRequest\"\x87\x01\n" +
	"\x12CoreStatusResponse\x12\x18\n" +
	"\aworking\x18\x01 \x01(\bR\aworking\x12\x19\n" +
	"\blast_log\x18\x02 \x01(\tR\alastLog\x12<\n" +
	"\fworking_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vworkingTime\"\x14\n" +
	"\x12CoreRestartRequest\"\x15\n" +
	"\x13CoreRestartResponse\"\x12\n" +
	"\x10GetConfigRequest\"'\n" +
	"\x11GetConfigResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"L\n" +
	"\x13UploadConfigRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12!\n" +
	"\frestart_core\x18\x02 \x01(\bR\vrestartCore\"\x16\n" +
	"\x14UploadConfigResponse*5\n" +
	"\x0eConnectionType\x12\v\n" +
	"\aINBOUND\x10\x00\x12\f\n" +
	"\bOUTBOUND\x10\x01\x12\b\n" +
	"\x04USER\x10\x02*%\n" +
	"\aNetType\x12\b\n" +
	"\x04HTTP\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x022\x80\x03\n" +
	"\x14CoreManagmentService\x12W\n" +
	"\n" +
	"CoreStatus\x12#.xraymon.commands.CoreStatusRequest\x1a$.xraymon.commands.CoreStatusResponse\x12Z\n" +
	"\vCoreRestart\x12$.xraymon.commands.CoreRestartRequest\x1a%.xraymon.commands.CoreRestartResponse\x12T\n" +
	"\tGetConfig\x12\".xraymon.commands.GetConfigRequest\x1a#.xraymon.commands.GetConfigResponse\x12]\n" +
	"\fUploadConfig\x12%.xraymon.commands.UploadConfigRequest\x1a&.xraymon.commands.UploadConfigResponse2\xb7\x02\n" +
	"\x0fJournalProvider\x12c\n" +
	"\x11ConnectionJournal\x12*.xraymon.commands.ConnectionJournalRequest\x1a .xraymon.commands.ConnectionMeta0\x01\x12]\n" +
	"\fNetworkStats\x12%.xraymon.commands.NetworkStatsRequest\x1a&.xraymon.commands.NetworkStatsResponse\x12`\n" +
	"\rRotateJournal\x12&.xraymon.commands.RotateJournalRequest\x1a'.xraymon.commands.RotateJournalResponseB>Z<github.com/eterline/xraymon/internal/interface/grpc/commandsb\x06proto3"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_commands_proto_goTypes = []any{
	(ConnectionType)(0),              // 0: xraymon.commands.ConnectionType
	(NetType)(0),                     // 1: xraymon.commands.NetType
	(*RotateJournalRequest)(nil),     // 2: xraymon.commands.RotateJournalRequest
	(*RotateJournalResponse)(nil),    // 3: xraymon.commands.RotateJournalResponse
	(*ConnectionIO)(nil),             // 4: xraymon.commands.ConnectionIO
	(*StatsMeta)(nil),                // 5: xraymon.commands.StatsMeta
	(*NetworkStatsResponse)(nil),     // 6: xraymon.commands.NetworkStatsResponse
	(*NetworkStatsRequest)(nil),      // 7: xraymon.commands.NetworkStatsRequest
	(*ConnectionJournalRequest)(nil), // 8: xraymon.commands.ConnectionJournalRequest
	(*ConnectionMeta)(nil),           // 9: xraymon.commands.ConnectionMeta
	(*CoreStatusRequest)(nil),        // 10: xraymon.commands.CoreStatusRequest
	(*CoreStatusResponse)(nil),       // 11: xraymon.commands.CoreStatusResponse
	(*CoreRestartRequest)(nil),       // 12: xraymon.commands.CoreRestartRequest
	(*CoreRestartResponse)(nil),      // 13: xraymon.commands.CoreRestartResponse
	(*GetConfigRequest)(nil),         // 14: xraymon.commands.GetConfigRequest
	(*GetConfigResponse)(nil),        // 15: xraymon.commands.GetConfigResponse
	(*UploadConfigRequest)(nil),      // 16: xraymon.commands.UploadConfigRequest
	(*UploadConfigResponse)(nil),     // 17: xraymon.commands.UploadConfigResponse
	(*durationpb.Duration)(nil),      // 18: google.protobuf.Duration
}
var file_commands_proto_depIdxs = []int32{
	0,  // 0: xraymon.commands.StatsMeta.type:type_name -> xraymon.commands.ConnectionType
	4,  // 1: xraymon.commands.StatsMeta.io:type_name -> xraymon.commands.ConnectionIO
	5,  // 2: xraymon.commands.NetworkStatsResponse.stats:type_name -> xraymon.commands.StatsMeta
	1,  // 3: xraymon.commands.ConnectionMeta.proto:type_name -> xraymon.commands.NetType
	18, // 4: xraymon.commands.CoreStatusResponse.working_time:type_name -> google.protobuf.Duration
	10, // 5: xraymon.commands.CoreManagmentService.CoreStatus:input_type -> xraymon.commands.CoreStatusRequest
	12, // 6: xraymon.commands.CoreManagmentService.CoreRestart:input_type -> xraymon.commands.CoreRestartRequest
	14, // 7: xraymon.commands.CoreManagmentService.GetConfig:input_type -> xraymon.commands.GetConfigRequest
	16, // 8: xraymon.commands.CoreManagmentService.UploadConfig:input_type -> xraymon.commands.UploadConfigRequest
	8,  // 9: xraymon.commands.JournalProvider.ConnectionJournal:input_type -> xraymon.commands.ConnectionJournalRequest
	7,  // 10: xraymon.commands.JournalProvider.NetworkStats:input_type -> xraymon.commands.NetworkStatsRequest
	2,  // 11: xraymon.commands.JournalProvider.RotateJournal:input_type -> xraymon.commands.RotateJournalRequest
	11, // 12: xraymon.commands.CoreManagmentService.CoreStatus:output_type -> xraymon.commands.CoreStatusResponse
	13, // 13: xraymon.commands.CoreManagmentService.CoreRestart:output_type -> xraymon.commands.CoreRestartResponse
	15, // 14: xraymon.commands.CoreManagmentService.GetConfig:output_type -> xraymon.commands.GetConfigResponse
	17, // 15: xraymon.commands.CoreManagmentService.UploadConfig:output_type -> xraymon.commands.UploadConfigResponse
	9,  // 16: xraymon.commands.JournalProvider.ConnectionJournal:output_type -> xraymon.commands.ConnectionMeta
	6,  // 17: xraymon.commands.JournalProvider.NetworkStats:output_type -> xraymon.commands.NetworkStatsResponse
	3,  // 18: xraymon.commands.JournalProvider.RotateJournal:output_type -> xraymon.commands.RotateJournalResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		EnumInfos:         file_commands_proto_enumTypes,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
