// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: commands.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetType int32

const (
	NetType_HTTP NetType = 0
	NetType_TCP  NetType = 1
	NetType_UDP  NetType = 2
)

// Enum value maps for NetType.
var (
	NetType_name = map[int32]string{
		0: "HTTP",
		1: "TCP",
		2: "UDP",
	}
	NetType_value = map[string]int32{
		"HTTP": 0,
		"TCP":  1,
		"UDP":  2,
	}
)

func (x NetType) Enum() *NetType {
	p := new(NetType)
	*p = x
	return p
}

func (x NetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetType) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[0].Descriptor()
}

func (NetType) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[0]
}

func (x NetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetType.Descriptor instead.
func (NetType) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

type ConnectionJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          uint64                 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionJournalRequest) Reset() {
	*x = ConnectionJournalRequest{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionJournalRequest) ProtoMessage() {}

func (x *ConnectionJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionJournalRequest.ProtoReflect.Descriptor instead.
func (*ConnectionJournalRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionJournalRequest) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

type ConnectionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=Server,proto3" json:"Server,omitempty"`
	Proto         NetType                `protobuf:"varint,3,opt,name=Proto,proto3,enum=xraymon.commands.NetType" json:"Proto,omitempty"`
	Inbound       string                 `protobuf:"bytes,4,opt,name=Inbound,proto3" json:"Inbound,omitempty"`
	Outbound      string                 `protobuf:"bytes,5,opt,name=Outbound,proto3" json:"Outbound,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMeta) Reset() {
	*x = ConnectionMeta{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMeta) ProtoMessage() {}

func (x *ConnectionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMeta.ProtoReflect.Descriptor instead.
func (*ConnectionMeta) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionMeta) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ConnectionMeta) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ConnectionMeta) GetProto() NetType {
	if x != nil {
		return x.Proto
	}
	return NetType_HTTP
}

func (x *ConnectionMeta) GetInbound() string {
	if x != nil {
		return x.Inbound
	}
	return ""
}

func (x *ConnectionMeta) GetOutbound() string {
	if x != nil {
		return x.Outbound
	}
	return ""
}

func (x *ConnectionMeta) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CoreStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusRequest) Reset() {
	*x = CoreStatusRequest{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusRequest) ProtoMessage() {}

func (x *CoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusRequest.ProtoReflect.Descriptor instead.
func (*CoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

type CoreStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Working       bool                   `protobuf:"varint,1,opt,name=Working,proto3" json:"Working,omitempty"`
	LastLog       string                 `protobuf:"bytes,2,opt,name=LastLog,proto3" json:"LastLog,omitempty"`
	WorkingTime   *durationpb.Duration   `protobuf:"bytes,3,opt,name=WorkingTime,proto3" json:"WorkingTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusResponse) Reset() {
	*x = CoreStatusResponse{}
	mi := &file_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusResponse) ProtoMessage() {}

func (x *CoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusResponse.ProtoReflect.Descriptor instead.
func (*CoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

func (x *CoreStatusResponse) GetWorking() bool {
	if x != nil {
		return x.Working
	}
	return false
}

func (x *CoreStatusResponse) GetLastLog() string {
	if x != nil {
		return x.LastLog
	}
	return ""
}

func (x *CoreStatusResponse) GetWorkingTime() *durationpb.Duration {
	if x != nil {
		return x.WorkingTime
	}
	return nil
}

type CoreRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreRestartRequest) Reset() {
	*x = CoreRestartRequest{}
	mi := &file_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreRestartRequest) ProtoMessage() {}

func (x *CoreRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreRestartRequest.ProtoReflect.Descriptor instead.
func (*CoreRestartRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{4}
}

type CoreRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreRestartResponse) Reset() {
	*x = CoreRestartResponse{}
	mi := &file_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreRestartResponse) ProtoMessage() {}

func (x *CoreRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreRestartResponse.ProtoReflect.Descriptor instead.
func (*CoreRestartResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{5}
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{6}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RestartCore   bool                   `protobuf:"varint,2,opt,name=RestartCore,proto3" json:"RestartCore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigRequest) Reset() {
	*x = UploadConfigRequest{}
	mi := &file_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigRequest) ProtoMessage() {}

func (x *UploadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigRequest.ProtoReflect.Descriptor instead.
func (*UploadConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{8}
}

func (x *UploadConfigRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadConfigRequest) GetRestartCore() bool {
	if x != nil {
		return x.RestartCore
	}
	return false
}

type UploadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigResponse) Reset() {
	*x = UploadConfigResponse{}
	mi := &file_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigResponse) ProtoMessage() {}

func (x *UploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigResponse.ProtoReflect.Descriptor instead.
func (*UploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{9}
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\x10xraymon.commands\x1a\x1egoogle/protobuf/duration.proto\".\n" +
	"\x18ConnectionJournalRequest\x12\x12\n" +
	"\x04last\x18\x01 \x01(\x04R\x04last\"\xbb\x01\n" +
	"\x0eConnectionMeta\x12\x16\n" +
	"\x06Client\x18\x01 \x01(\tR\x06Client\x12\x16\n" +
	"\x06Server\x18\x02 \x01(\tR\x06Server\x12/\n" +
	"\x05Proto\x18\x03 \x01(\x0e2\x19.xraymon.commands.NetTypeR\x05Proto\x12\x18\n" +
	"\aInbound\x18\x04 \x01(\tR\aInbound\x12\x1a\n" +
	"\bOutbound\x18\x05 \x01(\tR\bOutbound\x12\x12\n" +
	"\x04User\x18\x06 \x01(\tR\x04User\"\x13\n" +
	"\x11CoreStatusRequest\"\x85\x01\n" +
	"\x12CoreStatusResponse\x12\x18\n" +
	"\aWorking\x18\x01 \x01(\bR\aWorking\x12\x18\n" +
	"\aLastLog\x18\x02 \x01(\tR\aLastLog\x12;\n" +
	"\vWorkingTime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vWorkingTime\"\x14\n" +
	"\x12CoreRestartRequest\"\x15\n" +
	"\x13CoreRestartResponse\"\x12\n" +
	"\x10GetConfigRequest\"'\n" +
	"\x11GetConfigResponse\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\"K\n" +
	"\x13UploadConfigRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12 \n" +
	"\vRestartCore\x18\x02 \x01(\bR\vRestartCore\"\x16\n" +
	"\x14UploadConfigResponse*%\n" +
	"\aNetType\x12\b\n" +
	"\x04HTTP\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x022\xe5\x03\n" +
	"\x14CoreManagmentService\x12c\n" +
	"\x11ConnectionJournal\x12*.xraymon.commands.ConnectionJournalRequest\x1a .xraymon.commands.ConnectionMeta0\x01\x12W\n" +
	"\n" +
	"CoreStatus\x12#.xraymon.commands.CoreStatusRequest\x1a$.xraymon.commands.CoreStatusResponse\x12Z\n" +
	"\vCoreRestart\x12$.xraymon.commands.CoreRestartRequest\x1a%.xraymon.commands.CoreRestartResponse\x12T\n" +
	"\tGetConfig\x12\".xraymon.commands.GetConfigRequest\x1a#.xraymon.commands.GetConfigResponse\x12]\n" +
	"\fUploadConfig\x12%.xraymon.commands.UploadConfigRequest\x1a&.xraymon.commands.UploadConfigResponseB>Z<github.com/eterline/xraymon/internal/interface/grpc/commandsb\x06proto3"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_commands_proto_goTypes = []any{
	(NetType)(0),                     // 0: xraymon.commands.NetType
	(*ConnectionJournalRequest)(nil), // 1: xraymon.commands.ConnectionJournalRequest
	(*ConnectionMeta)(nil),           // 2: xraymon.commands.ConnectionMeta
	(*CoreStatusRequest)(nil),        // 3: xraymon.commands.CoreStatusRequest
	(*CoreStatusResponse)(nil),       // 4: xraymon.commands.CoreStatusResponse
	(*CoreRestartRequest)(nil),       // 5: xraymon.commands.CoreRestartRequest
	(*CoreRestartResponse)(nil),      // 6: xraymon.commands.CoreRestartResponse
	(*GetConfigRequest)(nil),         // 7: xraymon.commands.GetConfigRequest
	(*GetConfigResponse)(nil),        // 8: xraymon.commands.GetConfigResponse
	(*UploadConfigRequest)(nil),      // 9: xraymon.commands.UploadConfigRequest
	(*UploadConfigResponse)(nil),     // 10: xraymon.commands.UploadConfigResponse
	(*durationpb.Duration)(nil),      // 11: google.protobuf.Duration
}
var file_commands_proto_depIdxs = []int32{
	0,  // 0: xraymon.commands.ConnectionMeta.Proto:type_name -> xraymon.commands.NetType
	11, // 1: xraymon.commands.CoreStatusResponse.WorkingTime:type_name -> google.protobuf.Duration
	1,  // 2: xraymon.commands.CoreManagmentService.ConnectionJournal:input_type -> xraymon.commands.ConnectionJournalRequest
	3,  // 3: xraymon.commands.CoreManagmentService.CoreStatus:input_type -> xraymon.commands.CoreStatusRequest
	5,  // 4: xraymon.commands.CoreManagmentService.CoreRestart:input_type -> xraymon.commands.CoreRestartRequest
	7,  // 5: xraymon.commands.CoreManagmentService.GetConfig:input_type -> xraymon.commands.GetConfigRequest
	9,  // 6: xraymon.commands.CoreManagmentService.UploadConfig:input_type -> xraymon.commands.UploadConfigRequest
	2,  // 7: xraymon.commands.CoreManagmentService.ConnectionJournal:output_type -> xraymon.commands.ConnectionMeta
	4,  // 8: xraymon.commands.CoreManagmentService.CoreStatus:output_type -> xraymon.commands.CoreStatusResponse
	6,  // 9: xraymon.commands.CoreManagmentService.CoreRestart:output_type -> xraymon.commands.CoreRestartResponse
	8,  // 10: xraymon.commands.CoreManagmentService.GetConfig:output_type -> xraymon.commands.GetConfigResponse
	10, // 11: xraymon.commands.CoreManagmentService.UploadConfig:output_type -> xraymon.commands.UploadConfigResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		EnumInfos:         file_commands_proto_enumTypes,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
