// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: commands.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_Inbound  ConnectionType = 0
	ConnectionType_Outbound ConnectionType = 1
	ConnectionType_User     ConnectionType = 2
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "Inbound",
		1: "Outbound",
		2: "User",
	}
	ConnectionType_value = map[string]int32{
		"Inbound":  0,
		"Outbound": 1,
		"User":     2,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

type ConnectionIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesRX       uint64                 `protobuf:"varint,1,opt,name=BytesRX,proto3" json:"BytesRX,omitempty"`
	BytesTX       uint64                 `protobuf:"varint,2,opt,name=BytesTX,proto3" json:"BytesTX,omitempty"`
	BytesPerSecRx uint64                 `protobuf:"varint,3,opt,name=BytesPerSecRx,proto3" json:"BytesPerSecRx,omitempty"`
	BytesPerSecTx uint64                 `protobuf:"varint,4,opt,name=BytesPerSecTx,proto3" json:"BytesPerSecTx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionIO) Reset() {
	*x = ConnectionIO{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionIO) ProtoMessage() {}

func (x *ConnectionIO) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionIO.ProtoReflect.Descriptor instead.
func (*ConnectionIO) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionIO) GetBytesRX() uint64 {
	if x != nil {
		return x.BytesRX
	}
	return 0
}

func (x *ConnectionIO) GetBytesTX() uint64 {
	if x != nil {
		return x.BytesTX
	}
	return 0
}

func (x *ConnectionIO) GetBytesPerSecRx() uint64 {
	if x != nil {
		return x.BytesPerSecRx
	}
	return 0
}

func (x *ConnectionIO) GetBytesPerSecTx() uint64 {
	if x != nil {
		return x.BytesPerSecTx
	}
	return 0
}

type ConnectionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ConnectionType         `protobuf:"varint,1,opt,name=Type,proto3,enum=xraymon.commands.ConnectionType" json:"Type,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	IO            *ConnectionIO          `protobuf:"bytes,3,opt,name=IO,proto3" json:"IO,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMeta) Reset() {
	*x = ConnectionMeta{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMeta) ProtoMessage() {}

func (x *ConnectionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMeta.ProtoReflect.Descriptor instead.
func (*ConnectionMeta) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionMeta) GetType() ConnectionType {
	if x != nil {
		return x.Type
	}
	return ConnectionType_Inbound
}

func (x *ConnectionMeta) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ConnectionMeta) GetIO() *ConnectionIO {
	if x != nil {
		return x.IO
	}
	return nil
}

type ConnectionJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          uint64                 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionJournalRequest) Reset() {
	*x = ConnectionJournalRequest{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionJournalRequest) ProtoMessage() {}

func (x *ConnectionJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionJournalRequest.ProtoReflect.Descriptor instead.
func (*ConnectionJournalRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionJournalRequest) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

type CoreStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusRequest) Reset() {
	*x = CoreStatusRequest{}
	mi := &file_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusRequest) ProtoMessage() {}

func (x *CoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusRequest.ProtoReflect.Descriptor instead.
func (*CoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

type CoreStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Working       bool                   `protobuf:"varint,1,opt,name=Working,proto3" json:"Working,omitempty"`
	LastLog       string                 `protobuf:"bytes,2,opt,name=LastLog,proto3" json:"LastLog,omitempty"`
	WorkingTime   *durationpb.Duration   `protobuf:"bytes,3,opt,name=WorkingTime,proto3" json:"WorkingTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatusResponse) Reset() {
	*x = CoreStatusResponse{}
	mi := &file_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatusResponse) ProtoMessage() {}

func (x *CoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatusResponse.ProtoReflect.Descriptor instead.
func (*CoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{4}
}

func (x *CoreStatusResponse) GetWorking() bool {
	if x != nil {
		return x.Working
	}
	return false
}

func (x *CoreStatusResponse) GetLastLog() string {
	if x != nil {
		return x.LastLog
	}
	return ""
}

func (x *CoreStatusResponse) GetWorkingTime() *durationpb.Duration {
	if x != nil {
		return x.WorkingTime
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{5}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RestartCore   bool                   `protobuf:"varint,2,opt,name=RestartCore,proto3" json:"RestartCore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigRequest) Reset() {
	*x = UploadConfigRequest{}
	mi := &file_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigRequest) ProtoMessage() {}

func (x *UploadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigRequest.ProtoReflect.Descriptor instead.
func (*UploadConfigRequest) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{7}
}

func (x *UploadConfigRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadConfigRequest) GetRestartCore() bool {
	if x != nil {
		return x.RestartCore
	}
	return false
}

type UploadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadConfigResponse) Reset() {
	*x = UploadConfigResponse{}
	mi := &file_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfigResponse) ProtoMessage() {}

func (x *UploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfigResponse.ProtoReflect.Descriptor instead.
func (*UploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{8}
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\x10xraymon.commands\x1a\x1egoogle/protobuf/duration.proto\"\x8e\x01\n" +
	"\fConnectionIO\x12\x18\n" +
	"\aBytesRX\x18\x01 \x01(\x04R\aBytesRX\x12\x18\n" +
	"\aBytesTX\x18\x02 \x01(\x04R\aBytesTX\x12$\n" +
	"\rBytesPerSecRx\x18\x03 \x01(\x04R\rBytesPerSecRx\x12$\n" +
	"\rBytesPerSecTx\x18\x04 \x01(\x04R\rBytesPerSecTx\"\x8c\x01\n" +
	"\x0eConnectionMeta\x124\n" +
	"\x04Type\x18\x01 \x01(\x0e2 .xraymon.commands.ConnectionTypeR\x04Type\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\x12.\n" +
	"\x02IO\x18\x03 \x01(\v2\x1e.xraymon.commands.ConnectionIOR\x02IO\".\n" +
	"\x18ConnectionJournalRequest\x12\x12\n" +
	"\x04last\x18\x01 \x01(\x04R\x04last\"\x13\n" +
	"\x11CoreStatusRequest\"\x85\x01\n" +
	"\x12CoreStatusResponse\x12\x18\n" +
	"\aWorking\x18\x01 \x01(\bR\aWorking\x12\x18\n" +
	"\aLastLog\x18\x02 \x01(\tR\aLastLog\x12;\n" +
	"\vWorkingTime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vWorkingTime\"\x12\n" +
	"\x10GetConfigRequest\"'\n" +
	"\x11GetConfigResponse\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\"K\n" +
	"\x13UploadConfigRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12 \n" +
	"\vRestartCore\x18\x02 \x01(\bR\vRestartCore\"\x16\n" +
	"\x14UploadConfigResponse*5\n" +
	"\x0eConnectionType\x12\v\n" +
	"\aInbound\x10\x00\x12\f\n" +
	"\bOutbound\x10\x01\x12\b\n" +
	"\x04User\x10\x022\x89\x03\n" +
	"\x14CoreManagmentService\x12c\n" +
	"\x11ConnectionJournal\x12*.xraymon.commands.ConnectionJournalRequest\x1a .xraymon.commands.ConnectionMeta0\x01\x12W\n" +
	"\n" +
	"CoreStatus\x12#.xraymon.commands.CoreStatusRequest\x1a$.xraymon.commands.CoreStatusResponse\x12T\n" +
	"\tGetConfig\x12\".xraymon.commands.GetConfigRequest\x1a#.xraymon.commands.GetConfigResponse\x12]\n" +
	"\fUploadConfig\x12%.xraymon.commands.UploadConfigRequest\x1a&.xraymon.commands.UploadConfigResponseB>Z<github.com/eterline/xraymon/internal/interface/grpc/commandsb\x06proto3"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_commands_proto_goTypes = []any{
	(ConnectionType)(0),              // 0: xraymon.commands.ConnectionType
	(*ConnectionIO)(nil),             // 1: xraymon.commands.ConnectionIO
	(*ConnectionMeta)(nil),           // 2: xraymon.commands.ConnectionMeta
	(*ConnectionJournalRequest)(nil), // 3: xraymon.commands.ConnectionJournalRequest
	(*CoreStatusRequest)(nil),        // 4: xraymon.commands.CoreStatusRequest
	(*CoreStatusResponse)(nil),       // 5: xraymon.commands.CoreStatusResponse
	(*GetConfigRequest)(nil),         // 6: xraymon.commands.GetConfigRequest
	(*GetConfigResponse)(nil),        // 7: xraymon.commands.GetConfigResponse
	(*UploadConfigRequest)(nil),      // 8: xraymon.commands.UploadConfigRequest
	(*UploadConfigResponse)(nil),     // 9: xraymon.commands.UploadConfigResponse
	(*durationpb.Duration)(nil),      // 10: google.protobuf.Duration
}
var file_commands_proto_depIdxs = []int32{
	0,  // 0: xraymon.commands.ConnectionMeta.Type:type_name -> xraymon.commands.ConnectionType
	1,  // 1: xraymon.commands.ConnectionMeta.IO:type_name -> xraymon.commands.ConnectionIO
	10, // 2: xraymon.commands.CoreStatusResponse.WorkingTime:type_name -> google.protobuf.Duration
	3,  // 3: xraymon.commands.CoreManagmentService.ConnectionJournal:input_type -> xraymon.commands.ConnectionJournalRequest
	4,  // 4: xraymon.commands.CoreManagmentService.CoreStatus:input_type -> xraymon.commands.CoreStatusRequest
	6,  // 5: xraymon.commands.CoreManagmentService.GetConfig:input_type -> xraymon.commands.GetConfigRequest
	8,  // 6: xraymon.commands.CoreManagmentService.UploadConfig:input_type -> xraymon.commands.UploadConfigRequest
	2,  // 7: xraymon.commands.CoreManagmentService.ConnectionJournal:output_type -> xraymon.commands.ConnectionMeta
	5,  // 8: xraymon.commands.CoreManagmentService.CoreStatus:output_type -> xraymon.commands.CoreStatusResponse
	7,  // 9: xraymon.commands.CoreManagmentService.GetConfig:output_type -> xraymon.commands.GetConfigResponse
	9,  // 10: xraymon.commands.CoreManagmentService.UploadConfig:output_type -> xraymon.commands.UploadConfigResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		EnumInfos:         file_commands_proto_enumTypes,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
