// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: commands.proto

package commands

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreManagmentService_ConnectionJournal_FullMethodName = "/xraymon.commands.CoreManagmentService/ConnectionJournal"
	CoreManagmentService_CoreStatus_FullMethodName        = "/xraymon.commands.CoreManagmentService/CoreStatus"
	CoreManagmentService_GetConfig_FullMethodName         = "/xraymon.commands.CoreManagmentService/GetConfig"
	CoreManagmentService_UploadConfig_FullMethodName      = "/xraymon.commands.CoreManagmentService/UploadConfig"
)

// CoreManagmentServiceClient is the client API for CoreManagmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreManagmentServiceClient interface {
	ConnectionJournal(ctx context.Context, in *ConnectionJournalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionMeta], error)
	CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	UploadConfig(ctx context.Context, in *UploadConfigRequest, opts ...grpc.CallOption) (*UploadConfigResponse, error)
}

type coreManagmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreManagmentServiceClient(cc grpc.ClientConnInterface) CoreManagmentServiceClient {
	return &coreManagmentServiceClient{cc}
}

func (c *coreManagmentServiceClient) ConnectionJournal(ctx context.Context, in *ConnectionJournalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionMeta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreManagmentService_ServiceDesc.Streams[0], CoreManagmentService_ConnectionJournal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectionJournalRequest, ConnectionMeta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreManagmentService_ConnectionJournalClient = grpc.ServerStreamingClient[ConnectionMeta]

func (c *coreManagmentServiceClient) CoreStatus(ctx context.Context, in *CoreStatusRequest, opts ...grpc.CallOption) (*CoreStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoreStatusResponse)
	err := c.cc.Invoke(ctx, CoreManagmentService_CoreStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreManagmentServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, CoreManagmentService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreManagmentServiceClient) UploadConfig(ctx context.Context, in *UploadConfigRequest, opts ...grpc.CallOption) (*UploadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadConfigResponse)
	err := c.cc.Invoke(ctx, CoreManagmentService_UploadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreManagmentServiceServer is the server API for CoreManagmentService service.
// All implementations must embed UnimplementedCoreManagmentServiceServer
// for forward compatibility.
type CoreManagmentServiceServer interface {
	ConnectionJournal(*ConnectionJournalRequest, grpc.ServerStreamingServer[ConnectionMeta]) error
	CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	UploadConfig(context.Context, *UploadConfigRequest) (*UploadConfigResponse, error)
	mustEmbedUnimplementedCoreManagmentServiceServer()
}

// UnimplementedCoreManagmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreManagmentServiceServer struct{}

func (UnimplementedCoreManagmentServiceServer) ConnectionJournal(*ConnectionJournalRequest, grpc.ServerStreamingServer[ConnectionMeta]) error {
	return status.Error(codes.Unimplemented, "method ConnectionJournal not implemented")
}
func (UnimplementedCoreManagmentServiceServer) CoreStatus(context.Context, *CoreStatusRequest) (*CoreStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoreStatus not implemented")
}
func (UnimplementedCoreManagmentServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedCoreManagmentServiceServer) UploadConfig(context.Context, *UploadConfigRequest) (*UploadConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadConfig not implemented")
}
func (UnimplementedCoreManagmentServiceServer) mustEmbedUnimplementedCoreManagmentServiceServer() {}
func (UnimplementedCoreManagmentServiceServer) testEmbeddedByValue()                              {}

// UnsafeCoreManagmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreManagmentServiceServer will
// result in compilation errors.
type UnsafeCoreManagmentServiceServer interface {
	mustEmbedUnimplementedCoreManagmentServiceServer()
}

func RegisterCoreManagmentServiceServer(s grpc.ServiceRegistrar, srv CoreManagmentServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreManagmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreManagmentService_ServiceDesc, srv)
}

func _CoreManagmentService_ConnectionJournal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectionJournalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreManagmentServiceServer).ConnectionJournal(m, &grpc.GenericServerStream[ConnectionJournalRequest, ConnectionMeta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreManagmentService_ConnectionJournalServer = grpc.ServerStreamingServer[ConnectionMeta]

func _CoreManagmentService_CoreStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreManagmentServiceServer).CoreStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreManagmentService_CoreStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreManagmentServiceServer).CoreStatus(ctx, req.(*CoreStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreManagmentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreManagmentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreManagmentService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreManagmentServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreManagmentService_UploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreManagmentServiceServer).UploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreManagmentService_UploadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreManagmentServiceServer).UploadConfig(ctx, req.(*UploadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreManagmentService_ServiceDesc is the grpc.ServiceDesc for CoreManagmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreManagmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xraymon.commands.CoreManagmentService",
	HandlerType: (*CoreManagmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoreStatus",
			Handler:    _CoreManagmentService_CoreStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _CoreManagmentService_GetConfig_Handler,
		},
		{
			MethodName: "UploadConfig",
			Handler:    _CoreManagmentService_UploadConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectionJournal",
			Handler:       _CoreManagmentService_ConnectionJournal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "commands.proto",
}
